server:
  port: 8084

spring:
  application:
    name: price-calculator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    com.example.pricecalculatorservice: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

